//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesOfMovies
    {
        public int categoriesOfMovies_ID { get; set; }
        public int category_ID { get; set; }
        public int movie_ID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
