//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaHub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaHubDBEntities : DbContext
    {
        public CinemaHubDBEntities()
            : base("name=CinemaHubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriesOfMovies> CategoriesOfMovies { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Cinema> Cinema { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
    }
}
