//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticket_ID { get; set; }
        public Nullable<int> cinema_ID { get; set; }
        public Nullable<int> movie_ID { get; set; }
        public Nullable<int> user_ID { get; set; }
        public Nullable<int> seat_ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string session { get; set; }
        public string cardOwnerName { get; set; }
        public string cardNumber { get; set; }
        public string cardValidDate { get; set; }
        public string cardCVV { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
