//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccount()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int user_ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string userName { get; set; }
        public Nullable<bool> gender { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string password { get; set; }
        public Nullable<bool> userType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
